name: Publish Quarto Website

on:
  push:
    branches: [ main ]
    paths:
      - "**/*.qmd"
      - "_quarto.yml"
      - ".github/workflows/publish.yml"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions@v2.0.1
        with:
          command: publish